In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

arr1=np.array([1,2,3])
print(arr1)

[1 2 3]


In [6]:
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [7]:
o=np.ones((3,3))
print(o)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [11]:
rand=np.random.random((4,4))
print(rand)

[[0.50834121 0.86420647 0.37738199 0.09630622]
 [0.82405299 0.20634066 0.42694671 0.84761773]
 [0.12270182 0.07823802 0.59101072 0.63078239]
 [0.42980582 0.4182217  0.75068891 0.26273707]]


In [12]:
i=np.eye(3)
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
print("Shape:",arr2.shape)

Shape: (2, 3)


In [14]:
print("Size:",arr2.size)

Size: 6


In [15]:
print("Data Type",arr2.dtype)

Data Type int32


In [19]:
print("Dimension:",arr2.ndim)

Dimension: 2


In [22]:
arr2[:,1:]

array([[2, 3],
       [5, 6]])

In [25]:
arr2[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [30]:
arr3=np.array([1,2,3])
print(np.sqrt(arr3))

[1.         1.41421356 1.73205081]
